In [2]:
!pip install gym
!pip install pyglet==1.2.4
import numpy as np
import gym
import random 


     |████████████████████████████████| 964 kB 5.0 MB/s 
  Attempting uninstall: pyglet
    Found existing installation: pyglet 1.5.0
    Uninstalling pyglet-1.5.0:
      Successfully uninstalled pyglet-1.5.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gym 0.17.3 requires pyglet<=1.5.0,>=1.4.0, but you have pyglet 1.2.4 which is incompatible.


##Entorno

In [4]:
# Creamos el entorno
# Me da un error al poner Taxi-v2 y dice que la versión válida es la v3
env = gym.make("Taxi-v3")
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [5]:
#Cálculo de filas y columnas necesarias
action_size = env.action_space.n
state_size = env.observation_space.n
print("Columnas: " , action_size)
print("Filas: ", state_size)

Columnas:  6
Filas:  500


In [6]:
#Matriz de 6 columnas y 500 filas
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


##Q-Learning

El objetivo del Q-learning es aprender una serie de normas que le diga a un agente qué acción tomar bajo qué circunstancias. No requiere un modelo del entorno y puede manejar problemas con transiciones estocásticas y recompensas sin requerir adaptaciones. ​ Q-learning puede identificar una norma de acción-selección óptima para cualquier proceso de decisión, dado un tiempo de exploración infinito y una norma parcialmente aleatoria.

Ref: https://es.wikipedia.org/wiki/Q-learning



In [7]:
#Hiperparámetros
#Valores del repo
total_episodes = 50000
total_test_episodes = 100
max_steps  = 99

learning_rate = 0.7
gamma = 0.618

#Exploración
epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.01

In [8]:
#Algoritmo QLearning para taxi v3


for episode in range(total_episodes):
    
    state = env.reset()
    step = 0
    done = False
    
    for step in range(max_steps):
        # Randomizando
        exp_exp_tradeoff = random.uniform(0,1)
        
   
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])
        
      
        else:
            action = env.action_space.sample()
        
        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

      
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * 
                                    np.max(qtable[new_state, :]) - qtable[state, action])

        state = new_state
        

        if done == True: 
            break
    
   
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)


In [9]:
env.reset()
rewards = []

for episode in range(total_test_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0

    for step in range(max_steps):
        # Para que se visualice el juego a medida que avanzan los episodes.
        env.render()
        
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        total_rewards += reward
        
        if done:
            rewards.append(total_rewards)
            #print ("Score", total_rewards)
            break
        state = new_state
env.close()
print ("Score over time: " +  str(sum(rewards)/total_test_episodes))

Se han truncado las últimas 5000 líneas del flujo de salida.
|R: | : :G|
| : | : : |
|_: : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
|_: | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : :_|
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :

##Exploración y beneficio

El learning rate determina hasta qué punto la información adquirida sobrescribe la información vieja. Un factor de 0 hace que el agente no aprenda (únicamente aprovechando el conocimiento previo), mientras un factor de 1 hace que el agente considere solo la información más reciente (ignorando el conocimiento previo para explorar posibilidades).


##Optimización

Para optimizar el modelo se deben fijar valores de exploración adecuados 

Cuando el agente explora mejora su conocimiento y obtiene mejores recompensas en el largo plazo. 

El learning rate se deriva de estos conceptos y su variación afecta directametne al agente y su aprendizaje. Al modificar este parámetro cambia el tiempo de juego del agente. 

El score no es el mismo cada vez que se ejecuta el programa.

###Learning rate de 0.5

In [10]:
learning_rate = 0.5
for episode in range(total_episodes):
    
    state = env.reset()
    step = 0
    done = False
    
    for step in range(max_steps):
        # Randomizando
        exp_exp_tradeoff = random.uniform(0,1)
        
   
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])
        
      
        else:
            action = env.action_space.sample()
        
        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

      
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * 
                                    np.max(qtable[new_state, :]) - qtable[state, action])

        state = new_state
        

        if done == True: 
            break
    
   
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)

In [14]:
env.reset()
rewards = []

for episode in range(total_test_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0

    for step in range(max_steps):
        # Para que se visualice el juego a medida que avanzan los episodes.
        # Para entender mejor lo que significa cambiar el learning_rate, descomentar esto para ver el desarrollo del aprendizaje completo 
        #env.render()
        
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        total_rewards += reward
        
        if done:
            rewards.append(total_rewards)
            #print ("Score", total_rewards)
            break
        state = new_state
env.close()
print ("Score over time: " +  str(sum(rewards)/total_test_episodes))

Score over time: 8.2


###Learning rate de 0.1


In [15]:
learning_rate = 0.1
for episode in range(total_episodes):
    
    state = env.reset()
    step = 0
    done = False
    
    for step in range(max_steps):
        # Randomizando
        exp_exp_tradeoff = random.uniform(0,1)
        
   
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])
        
      
        else:
            action = env.action_space.sample()
        
        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

      
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * 
                                    np.max(qtable[new_state, :]) - qtable[state, action])

        state = new_state
        

        if done == True: 
            break
    
   
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)

In [16]:
env.reset()
rewards = []

for episode in range(total_test_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0

    for step in range(max_steps):
        # Para que se visualice el juego a medida que avanzan los episodes.
        # Para entender mejor lo que significa cambiar el learning_rate, descomentar esto para ver el desarrollo del aprendizaje completo 
        #env.render()
        
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        total_rewards += reward
        
        if done:
            rewards.append(total_rewards)
            #print ("Score", total_rewards)
            break
        state = new_state
env.close()
print ("Score over time: " +  str(sum(rewards)/total_test_episodes))

Score over time: 8.3
